### ISSUE TITLE
Feature request - random frames, random files.

### ISSUE THREAD

**Issue by simonjowett** [szantaii/slow-movie-frame-10.3#2]
Firstly - thanks for your hard work on this repository.  I've managed to load it up and get things working in around an hour or so.   It lovely to see the lovely grey scales on this 10.3" display.

I've also experimented with the Tom Whitewell repo and love some of the additional features that he has incorporated.  I've experimented with the random file and random frame options which, if you have a few movies in the folder gives a great variety to the artwork, and i wondered if this was possible to add in here?

I also have not checked but what is the behavior of the software if multiple files are in the 'videos' folder,  which is played and in what order/can it be specified.

**Comment by szantaii** [comment]
Hi @simonjowett,

First of all, thank you for your kind words. I am very happy to hear that someone else was able to setup this project!

You can put multiple video files into the &lsquo;videos&rsquo; directory and you can even arrange the videos in subdirectories (inside the &lsquo;videos&rsquo; directory.) The video files are sorted by their full paths using [Python's built-in `sorted()`](https://docs.python.org/3.9/library/functions.html#sorted) function.

Consider the following video files in the &lsquo;videos&rsquo; directory (`/videos` in this example):
* `/videos/video2.avi`
* `/videos/video1.mkv`
* `/videos/vvvvideo3.mp4`
* `/videos/vi/video3.mp4`

In this case after the first startup of the service a JSON file is created inside the &lsquo;videos&rsquo; directory containing some information about the videos. The video files are enumerated in this JSON file, sorted by their full paths. In this case the order of the videos would be the following:
1. `/videos/vi/video3.mp4`
2. `/videos/video1.mkv`
3. `/videos/video2.avi`
4. `/videos/vvvvideo3.mp4`

If you would like to set an order, then I would recommend to either put your video files into some number prefixed subdirectories or prepend some numbers to the video files to ensure the desired order of the videos, e.g.
1. `/videos/1000-video3.mp4`
2. `/videos/2000-video2.avi`
3. `/videos/3000-vvvvideo3.mp4`
4. `/videos/4000-video1.mkv`

Please note that once a video file was saved into the mentioned JSON file, it will keep its order, unless the video file is removed, or you manually edit the JSON file. If you would like to do the latter, then you should stop the `slow-movie-player.service`:

1. Stop the `slow-movie-player.service`:
   ```console
   sudo systemctl stop slow-movie-player.service
   ```

2. Edit the JSON file.

3. Start the `slow-movie-player.service`:
   ```console
   sudo systemctl start slow-movie-player.service
   ```

(If the JSON file exists then all new video files will be added to the end of the &lsquo;list.&rsquo;)

See the contents of the JSON file from my device:

```console
$ ls -ail /videos/videos.json 
7441922 -rwxr-xr-x 1 root root 357 May  8 21:22 /videos/videos.json
$ cat /videos/videos.json 
{
    "/videos/movie-1-1080p.mkv": {
        "frame_count": 148752,
        "duration": 6204197.999999999,
        "next_frame": 58949,
        "next_timestamp": 2458700.0
    },
    "/videos/movie-2-1080p.mkv": {
        "frame_count": 135193,
        "duration": 5638674.708333333,
        "next_frame": 0,
        "next_timestamp": 0.0
    }
}
```

Regarding the second part of your question, the random frames and random files. If I understand you correctly, then you would like to display random frames from a random the video file inside your &lsquo;videos&rsquo; directory, right? How would you like the following: I add a boolean type `random_frame` switch into the service config (with the default value `false`, or something like this) which you can turn on and then it will ensure the described behavior?

**Comment by simonjowett** [comment]
Hi Szantaii - thanks for the reply.  Yes, I noticed later in the day after making this comment that there is a json file created/enumerated in the videos folder.  The additional details you have provided help in understanding how multiple files will be handled.

Regarding the random file/random frame, your understanding is correct.  A boolean that can be set for random_frame would be what I'm looking for.  It turns the 'slow movie player' into a changing 'movie still' artwork.  The slow movie player concept is very cool (particularly for those associated videos showing them in time lapse), however, for a brief visitor to my home it's less cool and lacking in general interest and I've found it more engaging if the frame shows random shots from my favourite movies.

As a follow on (scope creep)! I'd probably incorporate a simple press button on a gpio pin to toggle between the slow movie player "std" which I can watch over the extended period then toggle to random_frames if I'm looking to demonstrate the frame for a friend/visitor.  I guess this could be done fairly simply with a script triggered off the push button?

**Comment by szantaii** [comment]
I have implemented the random frame feature. You can find it on the [add-random-frame-option](https://github.com/szantaii/slow-movie-frame-10.3/tree/add-random-frame-option) branch. To turn on the feature, you only have to enable the `random_frame` option, e.g. `random_frame = true`.

Please let me know if you have tried it. (Also, I would like to ask you to check the descriptions I have added to the config file and README regarding this option.)

Let me know if you need help.

**Comment by simonjowett** [comment]
OK - I did a clean install on a new SD card.  I'm not experienced in checking out different branches but followed your normal flow but after cloning your repository I followed it up with the command:
```
git checkout -b add-random-frame-option
```
I did not record the response but it looked ok. (no aparent errors)

I then followed the rest of your instructions and looked into the default.conf file and saw the new random parameter at the bottom of the file.  I copied across a couple of mp4 files and tested it out.

At first I could not seem to get it working.   However, after some time I realized through trial and error, that after making changes to the defaults.conf file the service needs to be restarted.   If this is the case I'd suggest a reference to this requirement in the instructions.

After discovering this I started to: 

Remove the service ```sudo ./setup.sh -u```
Make changes to the default.conf file
Reinstall the service ```sudo ./setup.sh -i```

Anyway, thanks for making the changes required - here comes a bit of randomness!
Simon

**Comment by szantaii** [comment]
Thanks for the feedback!

I will amend the documentation a bit with instructions how to modify the configuration (& restart the `slow-movie-player.service`, etc.) and will merge it to the `main` branch probably over the weekend.

I liked your idea about changing between the regular (continuous) and random frame playback modes. However, I do not intend to add a button (on GPIO) for this. Still, I have an idea for this. I already have a gist ([!shutdown-trigger.md](https://gist.github.com/szantaii/0cc5ee6d7a969e23eba7a42c243c979b)) to control shutdown for `slow-movie-frame-10.3`, and I will rework that to include the ability to change between the continuous and random frame playback modes. When I am done with that, you can connect your own remote and adapt the script for your own needs. (I hope that this is satisfactory.)

**Comment by simonjowett** [comment]
That sounds like a good plan.  I didn't realize the  Waveshare hat used all the GPIO's so using a remote with a wifi usb dongle is a great solution.  BTW the url link to the Rii i7 remote in your write up gives me a 404 error but I found it easily online and is still available [https://www.aliexpress.com/item/32756247275.html?spm=a2g0o.ppclist.product.40.6291fgiFfgiF7D&pdp_npi=2%40dis%21AUD%21AU%2432.33%21AU%2418.43%21%21%21%21%21%40210318ec16844174645232412ec835%2163767671583%21btf&_t=pvid:69f59176-5d9b-4362-ac33-af4470cb0345&afTraceInfo=32756247275__pc__pcBridgePPC__xxxxxx__1684417464](url)
It will take a few weeks for one to arrive (and I'll be away on a long trip from mid June), but let me know how you go and I'll test it out myself.

EDIT:  I remembered I have an old (and now unused) Flirc usb IR receiver,  I might be able to repurpose that.

**Comment by szantaii** [comment]
I have added a minor update to the README regarding configuration changes and merged all changes to the `main` branch.

I have also updated the previously mentioned gist (https://gist.github.com/szantaii/0cc5ee6d7a969e23eba7a42c243c979b) with the random frame playback controlling options.
